### ISSUE TITLE
not support 1.20.6

### ISSUE THREAD

**Issue by CuteLittleSky** [okocraft/Scoreboard-Folia#31]
[23:50:40 WARN]: [Scoreboard] Async task for Scoreboard v5.0-SNAPSHOT-mc1.20.4 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R3/entity/CraftPlayer
        at Scoreboard-5.0-SNAPSHOT-mc1.20.4.jar/net.okocraft.scoreboard.display.board.PacketBasedBoardDisplay.<init>(PacketBasedBoardDisplay.java:44) ~[
Scoreboard-5.0-SNAPSHOT-mc1.20.4.jar:?]
        at Scoreboard-5.0-SNAPSHOT-mc1.20.4.jar/net.okocraft.scoreboard.display.manager.PacketBasedDisplayManager.newDisplay(PacketBasedDisplayManager.j
ava:18) ~[Scoreboard-5.0-SNAPSHOT-mc1.20.4.jar:?]
        at Scoreboard-5.0-SNAPSHOT-mc1.20.4.jar/net.okocraft.scoreboard.display.manager.AbstractDisplayManager.showBoard(AbstractDisplayManager.java:26)
 ~[Scoreboard-5.0-SNAPSHOT-mc1.20.4.jar:?]
        at Scoreboard-5.0-SNAPSHOT-mc1.20.4.jar/net.okocraft.scoreboard.display.manager.AbstractDisplayManager.showDefaultBoard(AbstractDisplayManager.j
ava:37) ~[Scoreboard-5.0-SNAPSHOT-mc1.20.4.jar:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at Scoreboard-5.0-SNAPSHOT-mc1.20.4.jar/net.okocraft.scoreboard.ScoreboardPlugin.showDefaultBoardToOnlinePlayers(ScoreboardPlugin.java:208) ~[Sc
oreboard-5.0-SNAPSHOT-mc1.20.4.jar:?]
        at Scoreboard-5.0-SNAPSHOT-mc1.20.4.jar/net.okocraft.scoreboard.util.PlatformHelper.lambda$runAsync$0(PlatformHelper.java:78) ~[Scoreboard-5.0-S
NAPSHOT-mc1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer
        ... 19 more

**Comment by Siroshun09** [comment]
Unless Folia releases a dev-bundle (a dependency to access the internal code) for 1.20.6, we cannot publicly update Scoreboard-Folia.
When Folia's `dev/1.20.6` branch is merged into the master, this project will also be updated as soon as possible.

**Comment by Siroshun09** [comment]
An experimental Scoreboard-Folia build for 1.20.6 is now available [here](https://github.com/okocraft/Scoreboard-Folia/actions/runs/9327304135).
